baseURL: https://www.fluid.io/
languageCode: en-us
title: Fluid
theme: hugo-fresh

googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: Simplifying the development and management of APIs and Integrations
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/logo-dark.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Digital enabler
    # Hero subtitle (optional)
    subtitle: Simplificamos o desenvolvimento e gerenciamento de integrações e APIs
    # Button text
    buttontext: Comece já!
    # Where the main hero button links to
    buttonlink: "#contact"
    # Hero image (from static/images/___)
    image: illustrations/hero-img.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - cds
    - dydyo
    - hidroazul
    - jf
    - nogueira
    - rb
    - redevistorias
    # partnerlogos:
    - bling
    - flexy
    - huru
    - varejoonline
  
    # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  # - title: Features
  #   url: /
  # - title: Blog
  #   url: /blog
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  - title: Fale Conosco
    url: /#contact
    button: true
  
  # Describes the second "page" which you will see when you scroll down. Currently it will have always three titles.
  section1:
    title: Integração
    subtitle: Sem complicação
    tiles:
    - title: Developer Builder
      icon: laptop-cloud
      text: Portal com SDKs e construtor de automação para simplificar e acelerar o desenvolvimento de integrações.
      url: /
      buttonText: Free trial
    - title: Developer Admin
      icon: mouse-globe
      text: Acompanhe o status dos serviços, logs de transações e acelere o diagnóstico e solução em caso de falhas.
      url: /
      buttonText: Get started
    - title: Professional Services
      icon: plug-cloud
      text: Foque no que realmente importa para seu negócio e deixe a integração com nossos especialistas.
      url: /
      buttonText: Get started
  # Shows information why someone should use this product.
  section2:
    title: Quebrando barreiras
    subtitle: mais produtividade, receitas e menos silos para a verdadeira transformação digital
    features:
    - title: Fluid na sua logística
      text: Integre sua operação de vendas e distribuição com transportadoras, gateways de frete e _deliveries_.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Fluid no seu financeiro
      text: Integre Processos de Conciliação financeira, faturamento, contabilidade com toda empresa.
      icon: doc-sync
    - title: Fluid no seu E-commerce
      text: Conecte a sua operação de e-commerce com ERP, PDV, Maketplaces.
      icon: mobile-feed
    - title: Fluid no seu Atendimento
      text: Integre Sistemas de atendimento, assistência técnica, portal de auto atendimento e _chat_.
      icon: laptop-globe
    - title: Fluid no seu Marketing
      text: Compartilhe entre suas ferramentas de inbound, outbound e mídias sociais suas réguas de relacionamento e campanhas.
      icon: doc-sync
    - title: Fluid na sua Força de Vendas
      text: Automatize o envio de dados de preço para as suas aplicações de vendas, ERPs e CRMs.
      icon: mobile-feed
  # Display a bright image of your product.
  # section3: # TODO
  #   # title: Mais que uma plataforma, uma solução de integração
  #   subtitle: Mais que uma plataforma, uma solução de integração
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#contact"
  # What clients says about us.
  section4:
    title: Quem já está fluindo
    subtitle: Reduzindo custos, tempo de entrega de valor e inovando com a Fluid
    clients:
    - name: Rodrigo Azevedo
      quote: A solução da Fluid foi crucial para integrar nosso marketplace com nosso ERP Saibweb, como também com o ERP Bling de nosso parceiro.
      job: Gerente de TI
      company: Dydyo Refrigerantes
      img: rodrigo
    - name: André Pereira
      quote: A Fluid nos permitiu integrar a plataforma de E-Commerce com o ERP Totvs (situação que ficamos por quase dois anos com outro fornecedor sem sucesso). De uma forma simples, integramos produtos, estoques, valores, dados fiscais e implementamos processos de exceção.
      job: Gerente de Marketing
      company: NB Indústrias
      img: andre
    - name: Paul Eipper
      quote: A Fluid nos permitiu focar na evolução de nossa API, a qual é um diferencial importante de nosso serviços, enquanto delegamos a eles toda a complexidade do desenvolvimento e gestão da integração.
      job: Diretor de Tecnologia
      company: Rede Vistorias
      img: paul
  # Write us.
  section5: true

  footer:
    # Logo (from /images/logos/___)
    logo: logo-white.svg
    # TODO Show address and contact
    # Social Media Title
    socialmediatitle: Siga-nos
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://www.linkedin.com/company/fluid-digital-solutions/about/
      # Icons are from Font Awesome
      icon: linkedin
    - link: https://github.com/fluid-io
      icon: github
    # - link: https://facebook.com/#
    #   icon: facebook
    # - link: https://twitter.com/lucperkins
    #   icon: twitter
    bulmalogo: false
    quicklinks:
      # column1:
      #   title: "Product"
      #   links:
      #   - text: Discover features
      #     link: /
      #   - text: Why choose our product?
      #     link: /
      #   - text: Compare features
      #     link: /
      #   - text: Our roadmap
      #     link: /
      #   - text: AGB
      #     link: /agb
      # column2:
      #   title: "Docs"
      #   links:
      #   - text: Get started
      #     link: /
      #   - text: User guides
      #     link: /
      #   - text: Admin guide
      #     link: /
      #   - text: Developers
      #     link: /
      # column3:
      #   title: "Blog"
      #   links:
      #   - text: Latest news
      #     link: /blog/first
      #   - text: Tech articles
      #     link: /blog/second
